# Generated by Django 4.2.8 on 2024-01-03 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backblaze', '0003_alter_filemodel_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('post_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('sub_text', models.CharField(max_length=100)),
                ('Text', models.TextField()),
                ('photo', models.ForeignKey(limit_choices_to=models.Q(('category', 'image')), on_delete=django.db.models.deletion.CASCADE, to='backblaze.filemodel')),
            ],
        ),
    ]
