# Generated by Django 4.2.8 on 2024-01-04 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backblaze', '0003_alter_filemodel_category'),
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='photo',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('category', 'image')), null=True, on_delete=django.db.models.deletion.CASCADE, to='backblaze.filemodel'),
        ),
    ]
