# Generated by Django 4.2.8 on 2024-01-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_alter_newsmodel_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsmodel',
            name='Text',
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='url',
            field=models.CharField(default='https://www.facebook.com/profile.php?id=61553557254980', max_length=150),
            preserve_default=False,
        ),
    ]
