# Generated by Django 4.2.8 on 2024-01-21 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backblaze', '0003_alter_filemodel_category'),
        ('main_page', '0003_remove_newsmodel_text_newsmodel_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsmodel',
            options={'ordering': ['-post_at', '-update_at']},
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='sub_text_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='sub_text_uk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='title_uk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backblaze.filemodel')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
