# Generated by Django 4.2.8 on 2024-02-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_alter_newsmodel_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='website',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
