# Generated by Django 4.2.8 on 2024-02-21 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backblaze', '0004_alter_filemodel_url'),
        ('main_page', '0007_partners_website'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsmodel',
            options={'ordering': ['-post_at']},
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='sub_text',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='sub_text_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='sub_text_uk',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='title',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='title_en',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='title_uk',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='partners',
            name='logo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='backblaze.filemodel'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='website',
            field=models.URLField(max_length=300),
        ),
    ]
