# Generated by Django 4.2.8 on 2024-02-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_alter_newsmodel_options_alter_newsmodel_sub_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='sub_text',
            field=models.CharField(max_length=175),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='sub_text_en',
            field=models.CharField(max_length=175, null=True),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='sub_text_uk',
            field=models.CharField(max_length=175, null=True),
        ),
    ]
