# Generated by Django 4.2.8 on 2024-02-22 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backblaze', '0004_alter_filemodel_url'),
        ('main_page', '0009_alter_newsmodel_sub_text_alter_newsmodel_sub_text_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backblaze.filemodel'),
        ),
    ]
