# Generated by Django 4.2.8 on 2024-02-09 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dog_card', '0007_alter_dogcardmodel_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=20)),
                ('comment', models.TextField(blank=True, max_length=200, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('processing', models.BooleanField(default=False)),
                ('id_dog', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dog_card.dogcardmodel')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
