# Generated by Django 4.2.8 on 2024-02-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formcallback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackform',
            name='comment',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
