version: '3.8'

services:
  web:
    restart: always
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./:/app
      - /vol/web/media:/app/media
    command: >
      sh -c "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn server_DJ.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - web

  nginx:
    restart: always
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - web

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=django_db
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_password
    ports:
      - 5432:5432
    env_file:
      - .env

volumes:
  postgres_data:
  static_volume:
  media_volume:
