# Generated by Django 4.2.8 on 2024-01-26 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_usermini'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermini',
            old_name='is_aproved',
            new_name='is_approved',
        ),
        migrations.RemoveField(
            model_name='usermini',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usermini',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usermini',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='usermini',
            name='password',
        ),
        migrations.AddField(
            model_name='usermini',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usermini', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usermini',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
