# Generated by Django 4.2.8 on 2024-01-03 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backblaze', '0003_alter_filemodel_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog_card_model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('ready_for_adoption', models.BooleanField(default=False)),
                ('gender', models.CharField(choices=[('Пес', 'Пес'), ('Собачка', 'Собачка')], max_length=10)),
                ('age', models.CharField(max_length=20)),
                ('sterilization', models.BooleanField(default=False)),
                ('vaccination_parasite_treatment', models.BooleanField(default=False)),
                ('size', models.CharField(choices=[('Маленька', 'Маленькая'), ('Средняя', 'Средняя'), ('Велика', 'Велика')], max_length=10)),
                ('decription', models.TextField()),
                ('photo', models.ForeignKey(limit_choices_to=models.Q(('category', 'image')), on_delete=django.db.models.deletion.CASCADE, to='backblaze.filemodel')),
            ],
        ),
    ]
