# Generated by Django 4.2.8 on 2024-01-04 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backblaze', '0003_alter_filemodel_category'),
        ('dog_card', '0003_rename_decription_dogcardmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogcardmodel',
            name='photo',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('category', 'image')), null=True, on_delete=django.db.models.deletion.CASCADE, to='backblaze.filemodel'),
        ),
    ]
