# Generated by Django 4.2.8 on 2024-01-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_card', '0005_alter_dogcardmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogcardmodel',
            name='age_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dogcardmodel',
            name='age_uk',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dogcardmodel',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dogcardmodel',
            name='description_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dogcardmodel',
            name='gender_en',
            field=models.CharField(choices=[('хлопчик', 'хлопчик'), ('дівчинка', 'дівчинка')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dogcardmodel',
            name='gender_uk',
            field=models.CharField(choices=[('хлопчик', 'хлопчик'), ('дівчинка', 'дівчинка')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dogcardmodel',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dogcardmodel',
            name='name_uk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dogcardmodel',
            name='size_en',
            field=models.CharField(choices=[('Маленька', 'Маленькая'), ('Средняя', 'Средняя'), ('Велика', 'Велика')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dogcardmodel',
            name='size_uk',
            field=models.CharField(choices=[('Маленька', 'Маленькая'), ('Средняя', 'Средняя'), ('Велика', 'Велика')], max_length=10, null=True),
        ),
    ]
