# Generated by Django 4.2.8 on 2024-02-02 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backblaze', '0003_alter_filemodel_category'),
        ('dog_card', '0006_dogcardmodel_age_en_dogcardmodel_age_uk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogcardmodel',
            name='gender',
            field=models.CharField(choices=[('хлопчик', 'хлопчик'), ('дівчинка', 'дівчинка'), ('boy', 'boy'), ('girl', 'girl')], max_length=10),
        ),
        migrations.AlterField(
            model_name='dogcardmodel',
            name='gender_en',
            field=models.CharField(choices=[('хлопчик', 'хлопчик'), ('дівчинка', 'дівчинка'), ('boy', 'boy'), ('girl', 'girl')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dogcardmodel',
            name='gender_uk',
            field=models.CharField(choices=[('хлопчик', 'хлопчик'), ('дівчинка', 'дівчинка'), ('boy', 'boy'), ('girl', 'girl')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dogcardmodel',
            name='photo',
            field=models.ForeignKey(limit_choices_to=models.Q(('category', 'image')), null=True, on_delete=django.db.models.deletion.CASCADE, to='backblaze.filemodel'),
        ),
        migrations.AlterField(
            model_name='dogcardmodel',
            name='size',
            field=models.CharField(choices=[('маленький', 'маленький'), ('середній', 'середній'), ('великий', 'великий'), ('small', 'small'), ('medium', 'medium'), ('large', 'large')], max_length=10),
        ),
        migrations.AlterField(
            model_name='dogcardmodel',
            name='size_en',
            field=models.CharField(choices=[('маленький', 'маленький'), ('середній', 'середній'), ('великий', 'великий'), ('small', 'small'), ('medium', 'medium'), ('large', 'large')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dogcardmodel',
            name='size_uk',
            field=models.CharField(choices=[('маленький', 'маленький'), ('середній', 'середній'), ('великий', 'великий'), ('small', 'small'), ('medium', 'medium'), ('large', 'large')], max_length=10, null=True),
        ),
    ]
