# Generated by Django 4.2.8 on 2024-02-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_card', '0007_alter_dogcardmodel_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogcardmodel',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='dogcardmodel',
            name='name_en',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='dogcardmodel',
            name='name_uk',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
