# Generated by Django 4.2.8 on 2024-02-22 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backblaze', '0004_alter_filemodel_url'),
        ('dog_card', '0008_alter_dogcardmodel_name_alter_dogcardmodel_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogcardmodel',
            name='photo',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('category', 'image')), on_delete=django.db.models.deletion.CASCADE, to='backblaze.filemodel'),
        ),
    ]
