# Generated by Django 4.2.8 on 2024-01-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backblaze', '0003_alter_filemodel_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_of_animals', models.IntegerField()),
                ('quantity_of_employees', models.IntegerField()),
                ('quantity_of_succeeds_adoptions', models.IntegerField()),
                ('images', models.ManyToManyField(related_name='about_images', to='backblaze.filemodel')),
            ],
        ),
    ]
