# Generated by Django 4.2.8 on 2023-12-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backblaze', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
