# Generated by Django 4.2.8 on 2024-01-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backblaze', '0002_alter_filemodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='category',
            field=models.CharField(max_length=20),
        ),
    ]
