# Generated by Django 4.2.8 on 2024-02-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backblaze', '0003_alter_filemodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='url',
            field=models.URLField(),
        ),
    ]
